// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcze1i5eZN4hfm_ZvwKBMWOGzCkHGGL2s',
    appId: '1:289717582237:web:f633bc2bd5f5e7dbc29774',
    messagingSenderId: '289717582237',
    projectId: 'asistente-883d3',
    authDomain: 'asistente-883d3.firebaseapp.com',
    storageBucket: 'asistente-883d3.firebasestorage.app',
    measurementId: 'G-NMZSBDJ70R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTOSiksdcXCBQpu_UGirnxMuvI_0yuGE8',
    appId: '1:289717582237:android:20b581d04014e449c29774',
    messagingSenderId: '289717582237',
    projectId: 'asistente-883d3',
    storageBucket: 'asistente-883d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwATEFKNObT0dOZsKg3aE7QjU-qbcSs4g',
    appId: '1:289717582237:ios:4a2c7d7f3a83f49ec29774',
    messagingSenderId: '289717582237',
    projectId: 'asistente-883d3',
    storageBucket: 'asistente-883d3.firebasestorage.app',
    iosBundleId: 'com.example.proyectoProgramacionMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwATEFKNObT0dOZsKg3aE7QjU-qbcSs4g',
    appId: '1:289717582237:ios:4a2c7d7f3a83f49ec29774',
    messagingSenderId: '289717582237',
    projectId: 'asistente-883d3',
    storageBucket: 'asistente-883d3.firebasestorage.app',
    iosBundleId: 'com.example.proyectoProgramacionMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcze1i5eZN4hfm_ZvwKBMWOGzCkHGGL2s',
    appId: '1:289717582237:web:3589c60ef893b6c7c29774',
    messagingSenderId: '289717582237',
    projectId: 'asistente-883d3',
    authDomain: 'asistente-883d3.firebaseapp.com',
    storageBucket: 'asistente-883d3.firebasestorage.app',
    measurementId: 'G-QEBFD2YM92',
  );
}
