name: proyecto_programacion_movil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  image_picker: ^0.8.7+4
  google_mlkit_face_detection: ^0.5.0
  firebase_storage: ^12.4.6
  provider: ^6.1.1
  dialogflow_flutter: ^1.0.0
  http: ^0.13.6
  googleapis_auth: ^1.4.1
  fl_chart: ^1.0.0
  camera: ^0.10.0+1
  path_provider: ^2.0.11
  speech_to_text: ^6.3.0
  flutter_tts: ^3.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/clave_dialogflow.json